[package]
name = "chomp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cmp"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "0.3.2"
async-std = { version = "1.10.0", features = ["unstable"] }
capturing-glob = "0.1.1"
clap = "2.33.3"
derivative = "2.2.0"
futures = "0.3.18"
http = "0.2"
ipfs-api-backend-hyper = "0.2"
lazy_static = "1.4.0"
notify = "4.0.0"
num_cpus = "1.13.0"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.5"
