version = 0.1

[[task]]
  name = "svelte"
  template = "chomp:svelte"
  [task.args]
    indir = "test/src"
    outdir = "test/lib"

[[task]]
  name = "build:release"
  deps = ["build:templates"]
  run = "cargo build --release"

[[task]]
  name = "build"
  target = "target/Debug/chp.exe"
  deps = ["check-not-local", "build:templates"]
  run = "cargo build"

[[task]]
  name = "build:rust:release"
  target = "target/Release/chp.exe"
  deps = ["check-not-local", "build:templates"]
  run = "cargo build --release"

[[task]]
  name = "build:templates"
  run = """
    echo 'version = 0.1' > src/templates.toml
    cat templates/*.toml >> src/templates.toml
  """

[[task]]
  name = "check-not-local"
  engine = "node"
  run = """
    import path from 'path';
    if (process.env.CHOMP_PATH.startsWith(path.resolve('target'))) {
      console.error('Cannot build Chomp with local Chomp! Instead use the global "chp build".');
      process.exit(1);
    }
  """
