version = 0.1

[[task]]
  name = "install"
  deps = ["build"]
  run = """
    cp target/Debug/chp.exe ~/bin/chp2.exe
    cp target/Debug/chp.exe ~/bin/chp.exe
  """

[[task]]
  name = "build"
  deps = ["build:templates"]
  run = "cargo build"

[[task]]
  name = "build:templates"
  run = """
    echo 'version = 0.1' > src/templates.toml
    cat templates/*.toml >> src/templates.toml
  """
