version = 0.1

[env]
  build_type = "Debug"

[[task]]
  name = "build"
  target = "test/lib/#.js"
  deps = ["node_modules/.bin/swc", "test/src/#.ts"]
  run = "swc $DEP -o $TARGET"

[[task]]
  name = "install"
  target = "node_modules/.bin/swc"
  run = "npm install @swc/core @swc/cli --save-dev"
