version = 0.1

[[task]]
  name = "build"
  target = "target/Debug/cmp.exe"
  run = "cargo build"

[[task]]
  name = "test"
  deps = ["dep"]

[[task]]
  name = "dep"

[[task]]
  name = "install"
  deps = ["target/Debug/cmp.exe"]
  run = """
    cp target/Debug/cmp.exe ~/bin/
    # two copies since one is in use
    cp target/Debug/cmp.exe ~/bin/cmp2.exe
  """
