version = 0.1

[env]
  X = "1"

[[task]]
  name = "build"
  target = "target/Debug/chomp.exe"
  deps = ["check-not-local", "build:templates"]
  run = "cargo build"

[[task]]
  name = "build:release"
  target = "target/Release/chomp.exe"
  deps = ["check-not-local", "build:templates"]
  run = "cargo build --release"

[[task]]
  name = "build:templates"
  run = """
    echo 'version = 0.1' > src/templates.toml
    cat templates/*.toml >> src/templates.toml
  """

[[task]]
  name = "check-not-local"
  engine = "node"
  run = """
    import path from 'path';
    if (process.env.CHOMP_PATH.startsWith(path.resolve('target'))) {
      console.error('Cannot build Chomp with local Chomp! Instead use the global "chomp build".');
      process.exit(1);
    }
  """
