[[template]]
name = "babel"
definition = """({ autoInstall = false, presets = [], plugins = [], sourceMap = true, babelRc = true, configFile = null }) => [{
  deps: [...presets.map(p => `node_modules/${p}`), ...plugins.map(p => `node_modules/${p}`), 'node_modules/@babel/core', 'node_modules/@babel/cli'],
  run: `babel $DEP -o $TARGET${
      sourceMap ? ' --source-maps' : ''
    }${
      plugins.length ? ` --plugins=${plugins.join(',')}` : ''
    }${
      presets.length ? ` --presets=${presets.join(',')}` : ''
    }${
      !babelRc ? ' --no-babelrc' : ''
    }${
      configFile ? ` --config-file=${configFile.startsWith('./') ? configFile : './' + configFile}` : ''
    }`
}, {
  template: autoInstall ? 'npm:install' : 'npm:verify',
  args: {
    packages: [...presets.map(p => p.startsWith('@babel/') ? p + '@7' : p), ...plugins.map(p => p.startsWith('@babel/') ? p + '@7' : p), '@babel/core@7', '@babel/cli@7'],
    dev: true
  }
}];
"""
