[[template]]
  name = "chomp:jspm-generator"
  definition = """({ inHtmlFile, outHtmlFile, generatorEnv = ['browser', 'production', 'module'], ...generateOpts }) => [{
    target: outHtmlFile,
    deps: [inHtmlFile],
    engine: 'node',
    run: `
      import { Generator } from '@jspm/generator';
      import { readFile, writeFile } from 'fs/promises';
      import { pathToFileURL } from 'url';
      import mkdirp from 'mkdirp';
      import { dirname } from 'path';

      const generator = new Generator({
        mapUrl: pathToFileURL(outHtmlFile),
        env: generatorEnv
      });

      const htmlSource = await readFile(process.env.DEP, 'utf-8');
      const outHtml = await generator.htmlGenerate(htmlSource, generateOpts);

      mkdirp.sync(dirname(process.env.TARGET));
      await writeFile(process.env.TARGET, outHtml);
    `
  }, {
    template: 'chomp:npm:install',
    args: {
      packages: ['@jspm/generator', 'mkdirp'],
      dev: true
    }
  }]
  """
