[[template]]
  name = "chomp:jspm-generator"
  definition = """({ inHtmlFile, outHtmlFile, generatorEnv = ['browser', 'production', 'module'] }) => [{
    target: outHtmlFile,
    deps: [inHtmlFile],
    engine: 'node',
    run: `
      import { Generator } from '@jspm/generator';
      import { readFile, writeFile } from 'fs/promises';
      import { pathToFileURL } from 'url';
      import mkdirp from 'mkdirp';
      import { dirname } from 'path';

      const generator = new Generator({
        mapUrl: pathToFileURL(outHtmlFile),
        env: generatorEnv
      });

      let htmlSource = await readFile(process.env.DEP, 'utf-8');

      await generator.traceInstall('./main.js');

      const map = generator.getMap();

      htmlSource = htmlSource.replace('<script type="importmap"></script>', `<script type="importmap">${JSON.stringify(map, null, 2)}</script>`);

      mkdirp.sync(dirname(process.env.TARGET));
      await writeFile(process.env.TARGET, htmlSource);
    `
  }, {
    targets: ['node_modules/@jspm/generator', 'node_modules/mkdirp'],
    run: 'npm install @jspm/generator mkdirp --save-dev'
  }]
  """
