[[template]]
  name = "swc"
  definition = """() => [{
    deps: ['node_modules/@swc/core', 'node_modules/@swc/cli'],
    run: "swc $DEP -o $TARGET"
  }, {
    template: 'npm:install',
    args: {
      packages: ['@swc/core@1', '@swc/cli@0.1'],
      dev: true
    }
  }]
  """
